import Link from 'next/link'
import { ArrowRight, BarChart3, ShieldCheck, Coins, FileSignature, Bot, Database, FileCheck } from 'lucide-react'
import { ThemeToggle } from '@/components/features/theme-toggle'

export default function Landing() {
  return (
    <div className="min-h-screen">
      <nav className="border-b border-border">
        <div className="container flex h-14 items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-medium text-sm tracking-tight">
            <span className="text-gold">◆</span>
            <span>FedFMMatter</span>
          </Link>
          <div className="flex items-center gap-4 text-sm">
            <Link href="/dashboard" className="text-muted-foreground hover:text-foreground transition">Workspace</Link>
            <Link href="/dashboard/chat" className="text-muted-foreground hover:text-foreground transition">Ask</Link>
            <Link href="/about" className="text-muted-foreground hover:text-foreground transition">About</Link>
            <ThemeToggle />
          </div>
        </div>
      </nav>

      <section className="container py-20 md:py-32">
        <div className="max-w-3xl">
          <p className="text-xs font-medium tracking-[0.2em] uppercase text-gold mb-4">For federal financial management</p>
          <h1 className="text-4xl md:text-5xl font-medium tracking-tight leading-tight mb-6">
            An AI analyst for budget, audit, accounting, and contract work.
          </h1>
          <p className="text-lg text-muted-foreground leading-relaxed mb-8">
            Upload the documents you already work with — PB justifications, audit reports, financial statements, contract files. Get dashboards, insider analysis, and standard reporting generated by an agent that understands how federal programs actually work.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link href="/dashboard" className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground px-4 py-2 text-sm font-medium hover:opacity-90 transition">
              Open workspace <ArrowRight className="h-4 w-4" />
            </Link>
            <Link href="/dashboard/chat" className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2 text-sm hover:bg-accent transition">
              Ask the agent
            </Link>
          </div>
        </div>
      </section>

      <section className="container pb-20">
        <div className="mb-10 rounded-lg border border-border bg-card p-6 flex items-start gap-4 flex-wrap">
          <div className="flex-1 min-w-[240px]">
            <p className="text-[10px] font-medium tracking-[0.2em] uppercase text-gold mb-2">Featured reference</p>
            <h3 className="text-lg font-medium tracking-tight mb-1">FY 2027 Department of War Budget — inside analysis</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Topline architecture, the $350B mandatory tranche, procurement across 19 appropriation titles, MAC munitions, AI/autonomy portfolio, Advana → WDP restructuring, winners and losers, and execution risks.
            </p>
          </div>
          <Link href="/dashboard/budget/pb27" className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2 text-sm hover:bg-accent hover:border-primary/60 transition">
            Open analysis <ArrowRight className="h-4 w-4" />
          </Link>
        </div>

        <h2 className="text-2xl font-medium tracking-tight mb-6">Four practice areas</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <AreaCard
            href="/dashboard/budget"
            icon={BarChart3}
            title="Budget & Programs"
            copy="Program analysis, PB justifications, appropriation deep-dives, mandatory vs discretionary architecture."
          />
          <AreaCard
            href="/dashboard/audit"
            icon={ShieldCheck}
            title="Audit & Assurance"
            copy="Findings tracker, repeat-finding detection, CAP milestone status, unmodified-opinion readiness."
          />
          <AreaCard
            href="/dashboard/accounting"
            icon={Coins}
            title="Accounting & Execution"
            copy="Obligation rates, outlay tracking, ULO analysis, TAFS reconciliation, cancellation-risk surveillance."
          />
          <AreaCard
            href="/dashboard/contracts"
            icon={FileSignature}
            title="Contracts & Acquisition"
            copy="Contract cost review, FAR/DFARS compliance, EVM variance, competition analysis, performance scoring."
          />
        </div>
      </section>

      <section className="border-t border-border bg-muted/20">
        <div className="container py-16">
          <h2 className="text-2xl font-medium tracking-tight mb-8">How the agent works</h2>
          <div className="grid gap-6 md:grid-cols-3">
            <Feature icon={Database} title="Knowledge base" copy="Your uploaded documents are chunked, embedded into Neon pgvector, and served back to the agent via semantic search so answers are grounded in your source material." />
            <Feature icon={Bot} title="Multi-model waterfall" copy="Gemini 2.5 Flash Lite, with automatic failover to Groq Llama 3.3 70B, Llama 3.1 8B, and Gemini 2.0 Flash — so the agent stays responsive even when a provider is rate-limited." />
            <Feature icon={FileCheck} title="Standard reporting" copy="One-click generation of the report formats you already produce: budget briefings, audit summaries, contract cost analyses, dashboards." />
          </div>
        </div>
      </section>

      <footer className="border-t border-border">
        <div className="container py-8 text-xs text-muted-foreground flex flex-wrap gap-4 justify-between">
          <p>FedFMMatter — not affiliated with any federal agency. Do not upload classified or CUI material without appropriate authorization.</p>
          <div className="flex gap-4">
            <Link href="/about" className="hover:text-foreground">About</Link>
            <Link href="/contact" className="hover:text-foreground">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function AreaCard({ href, icon: Icon, title, copy }: { href: string; icon: any; title: string; copy: string }) {
  return (
    <Link href={href} className="group rounded-lg border border-border bg-card p-5 transition hover:border-primary/60 hover:-translate-y-0.5">
      <Icon className="h-5 w-5 mb-3 text-muted-foreground group-hover:text-primary transition" />
      <h3 className="font-medium text-sm mb-1">{title}</h3>
      <p className="text-xs text-muted-foreground leading-relaxed">{copy}</p>
    </Link>
  )
}

function Feature({ icon: Icon, title, copy }: { icon: any; title: string; copy: string }) {
  return (
    <div>
      <Icon className="h-5 w-5 mb-3 text-gold" />
      <h3 className="font-medium text-sm mb-2">{title}</h3>
      <p className="text-sm text-muted-foreground leading-relaxed">{copy}</p>
    </div>
  )
}
